### ISSUE TITLE
Recovery Time Objective (RTO)

### ISSUE THREAD

**Issue by davidmosaku** [learntocloud/cloud-dictionary#44] opened 2023-02-12 22:35 UTC
Fill out the JSON below with the following.

- word [REQUIRED]: The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.
- content [REQUIRED]: The definition. No more than 3 sentences.
- learn more URL [REQUIRED]: Page where people can visit to learn more about the word.
- tag [REQUIRED, select one]: Tech category the word fits in. Options: compute, security, service, general, analytics, developer tools, web, networking, database, storage, devops, ai/ml, identiy, iot, monitoring.
- abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.
- author name [REQUIRED]: Your name.
- author link [REQUIRED]: The URL you want your name to link to.

{
  "Recovery Time Objective": "",
  "RTO is the goal an organization plans as its maximum length of time it should take to restore services to normal operations in the event of an outage or data loss": "",
  "https://www.rubrik.com/insights/rto-rpo-whats-the-difference":"",
  "Disaster Recovery":"",
  "RTO": "",
  "David Mosaku":"",
  "https://www.linkedin.com/in/davidmosaku/": ""
}

**Comment by madebygps** [comment] 2023-02-13 13:18
Duplicate of https://github.com/learntocloud/cloud-dictionary/issues/46

Closing this one.

**Closed by madebygps** 2023-02-13 13:18 UTC
Labels: documentation, good first issue
